# Generated by Django 6.0.4 on 2026-04-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("category", models.CharField(max_length=100, verbose_name="Наименование категории")),
                ("description", models.TextField(verbose_name="Описание категории")),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("product_name", models.CharField(max_length=100, verbose_name="Наименование продукта")),
                ("description", models.TextField(verbose_name="Описание продукта")),
                ("product_image", models.ImageField(upload_to="", verbose_name="Изображение продукта")),
                ("category", models.CharField(max_length=100, verbose_name="Наименование категории продукта")),
                ("price", models.FloatField(verbose_name="Цена продукта")),
                ("created_at", models.DateField(verbose_name="Дата создания")),
                ("updated_at", models.DateField(verbose_name="Дата последнего изменения")),
            ],
        ),
    ]
