# Generated by Django 6.0.4 on 2026-04-12 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Наименование категории")),
                ("description", models.TextField(verbose_name="Описание категории")),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Наименование продукта")),
                ("description", models.TextField(verbose_name="Описание продукта")),
                ("image", models.ImageField(upload_to="", verbose_name="Изображение продукта")),
                ("price", models.FloatField(verbose_name="Цена продукта")),
                ("created_at", models.DateField(verbose_name="Дата создания")),
                ("updated_at", models.DateField(verbose_name="Дата последнего изменения")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="catalog.category", verbose_name="Категория"
                    ),
                ),
            ],
            options={
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
            },
        ),
    ]
