# Generated by Django 6.0.4 on 2026-04-12 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="category",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="product_image",
            new_name="image",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="product_name",
            new_name="name",
        ),
    ]
